### PR TITLE
Restructure source hierarchy

### PR DESCRIPTION
**Pull request by kovacsv**
Hi All! I recommend to use this hierarchy to make it easier to add new examples, and to update RhinoCompute.cs

- Only one solution with all of the example projects, and RhinoCompute as a class library
- No duplication of RhinoCompute.cs
- No duplication of editorconfig
- Updated NuGet package versions

### CODE REVIEW

**Comment by pearswj** [comment]
Hi @kovacsv, thanks for taking the time to submit this! I definitely agree that it would be good to avoid duplication of `RhinoCompute.cs`, however I think wrapping it in a class library over-complicates things. It would be easier to just reference the file from a common location.

Perhaps we should ship the Compute .NET API as a NuGet package instead (either as a compiled library or as source code, [similar to how Facebook's SimpleJson works](https://www.nuget.org/packages/SimpleJson/)).

Just my opinion... hopefully others will follow!

**Comment by kovacsv** [comment]
Ok, I understand your opinion, so I removed the class library and reference `RhinoCompute.cs` only as a linked file in both projects.

Of course a NuGet package would be the best option, but until it arrives this new structure would help me a lot because I plan to add some more examples.

**Comment by kovacsv** [comment]
Hello guys! Can you please tell me what are your plans with this pull request? Please let me know if you don't wanna accept it so I can write my examples in the old structure. Thanks, Viktor

**Comment by sbaer** [comment]
Hi Viktor, I plan on merging this PR. Just getting caught up after the holidays

**Comment by sbaer** [comment]
sorry about the delay @kovacsv . This PR has been merged and thanks again for cleaning things up

**Comment by kovacsv** [comment]
Thanks, Steve!

**Pull request merged**
